# -*- coding: utf-8 -*-
"""Total_data_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X0Sgh2iuJKijHijTA4G6nXf3Ov4DJi1J
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

pdata = pd.read_csv('match_data_3.csv')

pdata.columns

len(pdata.match_name.unique())

pdata.dtypes

pdata = pdata.astype({'match_country':'string'})
pdata = pdata.astype({'match_name':'string'})
pdata = pdata.astype({'name':'string'})
pdata = pdata.astype({'team1_name':'string'})
pdata = pdata.astype({'team2_name':'string'})
pdata = pdata.astype({'out_by':'string'})

pdata['country'] = pdata['match_country'].str[:-5]

pdata['country'].unique()

pdata['url'].value_counts()

pdata.isna().sum()

pdata = pdata.dropna()

pdata['name'].value_counts()

len(pdata['name'].unique())

pdata['team1_name'].value_counts()/11

country_names = pdata['country'].unique()
country_names

countries = {
  "india": 1,
  "bangladesh": 2,
  "new-zealand": 3,
  'west-indies': 4,
  'england': 5,
  'sri-lanka': 6,
  'australia-20':7
}
encoded_data = pdata['country'].apply(lambda col: col.map(countries[col.name]))
encoded_data

cdata = pdata

cdata = cdata.groupby(['name'])

pdata.columns

average_strike_rate = pdata.groupby(['name'])['strike_rate'].mean()
average_strike_rate

cdata.get_group('Virat Kohli')

cdata.get_group('Virat Kohli')['strike_rate'].mean()





