# -*- coding: utf-8 -*-
"""Total_data_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X0Sgh2iuJKijHijTA4G6nXf3Ov4DJi1J
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

pdata = pd.read_csv('match_data_3.csv')

pdata.columns

len(pdata.match_name.unique())

pdata.dtypes

pdata = pdata.astype({'match_country':'string'})
pdata = pdata.astype({'match_name':'string'})
pdata = pdata.astype({'name':'string'})
pdata = pdata.astype({'team1_name':'string'})
pdata = pdata.astype({'team2_name':'string'})
pdata = pdata.astype({'out_by':'string'})

pdata['country'] = pdata['match_country'].str[:-5]

pdata['country'].unique()

pdata['url'].value_counts()

pdata.isna().sum()

pdata = pdata.dropna()

pdata['name'].value_counts()

len(pdata['name'].unique())

## Encoding categorical variables 
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()

xdata = pdata
# Encode labels in column 'species'.
xdata['country']= label_encoder.fit_transform(xdata['country'])
  
xdata['country'].unique()
xdata

