# -*- coding: utf-8 -*-
"""Player_Country.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qfd4HesAF1AasqcXkq2YsPmQB2Rv44dH
"""

import pandas as pd
import numpy as np

data = pd.read_csv('match_data_3.csv')
# data.head()

## name and team_name
player_country = data.loc[:, ['name', 'team_name']]

player_country = player_country.drop_duplicates()

# return player_country
print(player_country)

## player_country contains what you need

player_country['name'].value_counts()